project:
  type: book

book:
  title: "<%= title %>"
  author: "Jane Doe"
  date: "<%= new Date().toLocaleDateString() %>"
  chapters:
    - index<%= ext %>
    - intro<%= ext %>
    - summary<%= ext %>
    - references<%= ext %>

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport

<% if(editor){ %>editor: <%= editor %><% } %>
